# Generated by Django 5.2.14 on 2026-05-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
